# Generated by Django 6.0.7 on 2026-07-22 17:34

import ckeditor.fields
import cloudinary.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_enum.fields
import nekusoracinema.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('opening_time', models.TimeField(default='08:00')),
                ('closing_time', models.TimeField(default='24:00')),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScreeningFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', django_enum.fields.EnumCharField(choices=[('ADMIN', 'ADMIN'), ('CUSTOMER', 'CUSTOMER'), ('STAFF', 'STAFF'), ('MANAGER', 'MANAGER')], default='CUSTOMER', max_length=8)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', django_enum.fields.EnumCharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=6, null=True)),
                ('avatar', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('loyalty_points', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_code', models.CharField(default=nekusoracinema.models.generate_booking_code, max_length=20, unique=True)),
                ('status', django_enum.fields.EnumCharField(choices=[('HOLDING', 'HOLDING'), ('CONFIRMED', 'CONFIRMED'), ('CANCELLED', 'CANCELLED'), ('EXPIRED', 'EXPIRED')], default='HOLDING', max_length=9)),
                ('seat_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('product_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('points_used', models.PositiveIntegerField(default=0)),
                ('points_used_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('final_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('held_until', models.DateTimeField(help_text='Thời điểm hết hạn giữ ghế = created_at + 7 mins')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('is_checked_in', models.BooleanField(default=False)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_by', models.ForeignKey(blank=True, help_text='Nhân viên soát vé đã quét mã', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_bookings', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CinemaRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('total_rows', models.PositiveSmallIntegerField(default=10)),
                ('seats_per_row', models.PositiveSmallIntegerField(default=12)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='nekusoracinema.branch')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='nekusoracinema.location'),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('age_rating', django_enum.fields.EnumCharField(choices=[('P', 'P'), ('K', 'K'), ('T13', 'T13'), ('T16', 'T16'), ('T18', 'T18')], max_length=3)),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('release_date', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=150)),
                ('description', ckeditor.fields.RichTextField()),
                ('poster_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('trailer_url', models.URLField()),
                ('status', django_enum.fields.EnumCharField(choices=[('COMING_SOON', 'COMING_SOON'), ('NOW_SHOWING', 'NOW_SHOWING'), ('ENDED', 'ENDED')], default='COMING_SOON', max_length=11)),
                ('genres', models.ManyToManyField(related_name='movies', to='nekusoracinema.genre')),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='MovieActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character_name', models.CharField(blank=True, max_length=150)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nekusoracinema.actor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nekusoracinema.movie')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movies', through='nekusoracinema.MovieActor', to='nekusoracinema.actor'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('transaction_ref', models.CharField(blank=True, help_text='Mã giao dịch từ cổng thanh toán', max_length=100)),
                ('status', django_enum.fields.EnumCharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILED'), ('REFUNDED', 'REFUNDED')], default='PENDING', max_length=8)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='nekusoracinema.booking')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nekusoracinema.paymentmethod')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points', models.IntegerField(help_text='Dương = cộng điểm, Âm = trừ điểm')),
                ('transaction_type', django_enum.fields.EnumCharField(choices=[('EARN', 'EARN'), ('REDEEM', 'REDEEM'), ('ADJUST', 'ADJUST')], max_length=6)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='nekusoracinema.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('product_type', django_enum.fields.EnumCharField(choices=[('SINGLE', 'SINGLE'), ('COMBO', 'COMBO')], max_length=6)),
            ],
            options={
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('product_type__in', ['SINGLE', 'COMBO'])), name='nekusoracinema_Product_product_type_ProductType')],
            },
        ),
        migrations.CreateModel(
            name='ComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('combo', models.ForeignKey(limit_choices_to={'product_type': 'COMBO'}, on_delete=django.db.models.deletion.CASCADE, related_name='combo_items', to='nekusoracinema.product')),
                ('item', models.ForeignKey(limit_choices_to={'product_type': 'SINGLE'}, on_delete=django.db.models.deletion.CASCADE, related_name='included_in_combos', to='nekusoracinema.product')),
            ],
        ),
        migrations.CreateModel(
            name='BookingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_products', to='nekusoracinema.booking')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nekusoracinema.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('discount_type', django_enum.fields.EnumCharField(choices=[('PERCENT', 'PERCENT'), ('FIXED_AMOUNT', 'FIXED_AMOUNT')], max_length=12)),
                ('discount_value', models.DecimalField(decimal_places=0, max_digits=10)),
                ('min_order_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('discount_type__in', ['PERCENT', 'FIXED_AMOUNT'])), name='nekusoracinema_Promotion_discount_type_PromotionDiscountType')],
            },
        ),
        migrations.CreateModel(
            name='BookingPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_promotions', to='nekusoracinema.booking')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nekusoracinema.promotion')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('comment', models.TextField(blank=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='nekusoracinema.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
                ('verified_booking', models.ForeignKey(blank=True, help_text='Booking đã check-in dùng để chứng minh đủ điều kiện đánh giá.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nekusoracinema.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_label', models.CharField(max_length=2)),
                ('seat_number', models.PositiveSmallIntegerField()),
                ('seat_code', models.CharField(max_length=10)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='nekusoracinema.cinemaroom')),
            ],
            options={
                'ordering': ['room', 'row_label', 'seat_number'],
            },
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('show_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('base_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('status', django_enum.fields.EnumCharField(choices=[('SCHEDULED', 'SCHEDULED'), ('CANCELLED', 'CANCELLED'), ('COMPLETED', 'COMPLETED')], default='SCHEDULED', max_length=9)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_showtimes', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='nekusoracinema.movie')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='nekusoracinema.cinemaroom')),
                ('screening_format', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nekusoracinema.screeningformat')),
            ],
            options={
                'ordering': ['show_date', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='showtime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='nekusoracinema.showtime'),
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', django_enum.fields.EnumCharField(choices=[('COUNTER_STAFF', 'COUNTER_STAFF'), ('CHECKER_STAFF', 'CHECKER_STAFF'), ('BRANCH_MANAGER', 'BRANCH_MANAGER'), ('SYSTEM_MANAGER', 'SYSTEM_MANAGER')], max_length=14)),
                ('hire_date', models.DateField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='nekusoracinema.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('status', django_enum.fields.EnumCharField(choices=[('HELD', 'HELD'), ('BOOKED', 'BOOKED'), ('CANCELLED', 'CANCELLED')], default='HELD', max_length=9)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='nekusoracinema.booking')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='nekusoracinema.seat')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='nekusoracinema.showtime')),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['ADMIN', 'CUSTOMER', 'STAFF', 'MANAGER'])), name='nekusoracinema_User_role_UserRole'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('gender__in', ['MALE', 'FEMALE', 'OTHER']), ('gender__isnull', True), _connector='OR'), name='nekusoracinema_User_gender_Gender'),
        ),
        migrations.AlterUniqueTogether(
            name='cinemaroom',
            unique_together={('branch', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='movieactor',
            unique_together={('movie', 'actor')},
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.CheckConstraint(condition=models.Q(('age_rating__in', ['P', 'K', 'T13', 'T16', 'T18'])), name='nekusoracinema_Movie_age_rating_MovieAgeRating'),
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['COMING_SOON', 'NOW_SHOWING', 'ENDED'])), name='nekusoracinema_Movie_status_MovieStatus'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'SUCCESS', 'FAILURE', 'REFUNDED'])), name='nekusoracinema_Payment_status_PaymentStatus'),
        ),
        migrations.AddConstraint(
            model_name='pointtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('transaction_type__in', ['EARN', 'REDEEM', 'ADJUST'])), name='oracinema_PointTransaction_transaction_type_PointTransactionType'),
        ),
        migrations.AlterUniqueTogether(
            name='comboitem',
            unique_together={('combo', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='bookingpromotion',
            unique_together={('booking', 'promotion')},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'movie')},
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('room', 'row_label', 'seat_number')},
        ),
        migrations.AddIndex(
            model_name='showtime',
            index=models.Index(fields=['movie', 'show_date'], name='nekusoracin_movie_i_d71108_idx'),
        ),
        migrations.AddConstraint(
            model_name='showtime',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['SCHEDULED', 'CANCELLED', 'COMPLETED'])), name='nekusoracinema_Showtime_status_ShowtimeStatus'),
        ),
        migrations.AlterUniqueTogether(
            name='showtime',
            unique_together={('room', 'show_date', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer', 'status', 'created_at'], name='nekusoracin_custome_f12eaa_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['HOLDING', 'CONFIRMED', 'CANCELLED', 'EXPIRED'])), name='nekusoracinema_Booking_status_BookingStatus'),
        ),
        migrations.AddConstraint(
            model_name='staffprofile',
            constraint=models.CheckConstraint(condition=models.Q(('position__in', ['COUNTER_STAFF', 'CHECKER_STAFF', 'BRANCH_MANAGER', 'SYSTEM_MANAGER'])), name='nekusoracinema_StaffProfile_position_StaffPosition'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['HELD', 'BOOKED'])), fields=('showtime', 'seat'), name='unique_active_seat_per_showtime'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['HELD', 'BOOKED', 'CANCELLED'])), name='nekusoracinema_Ticket_status_TicketStatus'),
        ),
    ]
