# Generated by Django 6.0.7 on 2026-07-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nekusoracinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, max_length=280, unique=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, max_length=280, unique=True),
        ),
    ]
