# Generated by Django 6.0.7 on 2026-07-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nekusoracinema', '0004_alter_movie_trailer_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='duration_minutes',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='poster_image',
            new_name='poster',
        ),
        migrations.RenameField(
            model_name='showtime',
            old_name='base_price',
            new_name='price',
        ),
    ]
