# Generated by Django 6.0.7 on 2026-08-04 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nekusoracinema', '0006_alter_booking_customer_alter_booking_showtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='per_user_limit',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='held_until',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bookingpromotion',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_promotion', to='nekusoracinema.booking'),
        ),
        migrations.CreateModel(
            name='PromotionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_usage_records', to='nekusoracinema.booking')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_usages', to='nekusoracinema.promotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_promotion_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['promotion', 'user'], name='nekusoracin_promoti_6cef6d_idx')],
            },
        ),
    ]
