# Generated by Django 6.0.7 on 2026-08-18 17:16

import nekusoracinema.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nekusoracinema', '0008_payment_cancel_reason_payment_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(default=nekusoracinema.utils.generate_booking_code, max_length=20, unique=True),
        ),
    ]
