# Generated by Django 6.0.7 on 2026-08-24 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nekusoracinema', '0009_alter_booking_booking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pointtransaction',
            name='points',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='verified_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nekusoracinema.booking'),
        ),
    ]
